server:
  port: 3301

spring:
  application:
    name: config-single-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/github-lujun/config-only-a-demo #配置文件所在仓库
          username: 838587241@qq.com #登录账号
          password: 220422a006n #登录密码
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录